version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: 'db'
      DB_USER: 'root'
      DB_PASS: 'pass'
      DB_NAME: 'data'
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    volumes:
      - dev-db-data:/var/lib/mysqlservice/data
    environment:
        MYSQL_DATABASE: 'data'
        MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - "3306:3306"

volumes:
  dev-db-data: