# Generated by Django 5.0.6 on 2024-07-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=255)),
                ('show_desc', models.CharField(max_length=512)),
                ('date_of_completion', models.DateField(auto_now_add=True)),
                ('is_series', models.BooleanField(default=False)),
                ('is_anime', models.BooleanField(default=True)),
            ],
        ),
    ]
